apiVersion: v1
kind: Secret
metadata:
  name: sundaland-admin-token
  namespace: sundaland
stringData:
  SUNDALAND_ADMIN_TOKEN: "your-admin-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-mongodb-credentials
  namespace: sundaland
stringData:
  SUNDALAND_MONGODB_USER: "admin"
  SUNDALAND_MONGODB_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-pull-secret
  namespace: sundaland
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "your_auth"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
