apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sundaland
resources:
  - deployment.yml
  - ingress.yml
  - secrets.yml
  - service.yml
configMapGenerator:
  - name: sundaland-backend-config-HASH
    literals:
      - SUNDALAND_MONGODB_DATABASE=Sundaland
      - SUNDALAND_MONGODB_HOST=mongodb.sundaland.svc.cluster.local
