apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sundaland
resources:
  - secrets.yml
  - service.yml
  - statefulset.yml
configMapGenerator:
  - name: mongodb-initdb-HASH
    files:
      - init.js
