apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: sundaland
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.cri.epita.fr/ing/majeures/tc/info/sundaland/mongo:7.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-admin-credentials
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-admin-credentials
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "Sundaland"
        - name: SUNDALAND_MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: sundaland-mongodb-credentials
              key: SUNDALAND_MONGODB_USER
        - name: SUNDALAND_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sundaland-mongodb-credentials
              key: SUNDALAND_MONGODB_PASSWORD
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: data
          mountPath: /data/db
      volumes:
      - name: initdb
        configMap:
          name: mongodb-initdb
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
